// <auto-generated />
namespace Mas_Logistics_Company.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class littleupd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(littleupd));
        
        string IMigrationMetadata.Id
        {
            get { return "201706192102470_littleupd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
